# vim: set sw=4 ts=4 sts=4 et :
# Copyright 2010 Ali Polatel <alip@exherbo.org>
# Distributed under the terms of the GNU Lesser General Public License v2.1

# Process this file with Cython.

cdef extern from "pinktrace/pink.h":
    cdef enum:
        PINKTRACE_VERSION
        PINKTRACE_VERSION_MAJOR
        PINKTRACE_VERSION_MINOR
        PINKTRACE_VERSION_MICRO

    cdef enum:
        PINKTRACE_ARCH_I386
        PINKTRACE_ARCH_X86_64
        PINKTRACE_ARCH_IA64
        PINKTRACE_ARCH_POWERPC
        PINKTRACE_ARCH_POWERPC64

    char *PINKTRACE_VERSION_SUFFIX
    char *PINKTRACE_GIT_HEAD
    char *PINKTRACE_ARCHITECTURE

VERSION_MAJOR = PINKTRACE_VERSION_MAJOR
VERSION_MINOR = PINKTRACE_VERSION_MINOR
VERSION_MICRO = PINKTRACE_VERSION_MICRO
VERSION_SUFFIX = PINKTRACE_VERSION_SUFFIX
VERSION = PINKTRACE_VERSION
GIT_HEAD = PINKTRACE_GIT_HEAD
ARCHITECTURE = PINKTRACE_ARCHITECTURE

if PINKTRACE_ARCH_I386 != 0:
    ARCH_I386 = True
else:
    ARCH_I386 = False

if PINKTRACE_ARCH_X86_64 != 0:
    ARCH_X86_64 = True
else:
    ARCH_X86_64 = False

if PINKTRACE_ARCH_IA64 != 0:
    ARCH_IA64 = True
else:
    ARCH_IA64 = False

if PINKTRACE_ARCH_POWERPC != 0:
    ARCH_POWERPC = True
else:
    ARCH_POWERPC = False

if PINKTRACE_ARCH_POWERPC64 != 0:
    ARCH_POWERPC64 = True
else:
    ARCH_POWERPC64 = False
